# Repaso de la Librería NumPy

In [1]:
import numpy as np

## Arreglos en Numpy

## Creando una lista en python

In [2]:
my_list = [1,2,3]

In [3]:
my_list

[1, 2, 3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Métodos incorporados en Numpy

### arange
Devuelve valores espaciados uniformemente dentro de un intervalo definido [referencia](https://numpy.org/doc/stable/reference/generated/numpy.arange.html?highlight=arange#numpy.arange)

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### Arreglos de ceros (Zeros) y Unos (Ones)

podemos generar matrices de ceros ó unos [referencia](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html?highlight=zeros#numpy.zeros)

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones(3)

array([1., 1., 1.])

In [13]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
1/2*np.ones((5,5))

array([[0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5]])

### Linspace
este método devuelve números espaciados uniformemente durante un intervalo especificado [referencia](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html?highlight=linspace#numpy.linspace)

In [15]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [16]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

### eye
mediante este método podemos crear la matriz identidad. [referencia](https://numpy.org/doc/stable/reference/generated/numpy.eye.html?highlight=eye#numpy.eye)

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Random
método que nos sirve para crear arreglos de número aleatorios

#### rand

Crea un arreglo de un tamaño dado con muestras aleatorias con una distribución uniforme en el intervalo $[0,1)$ [referencia](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html?highlight=rand#numpy.random.rand)

In [18]:
np.random.rand(2)

array([0.48549097, 0.17453144])

In [19]:
np.random.rand(5,5)

array([[0.94210261, 0.62854227, 0.79304592, 0.78156675, 0.71468524],
       [0.64308797, 0.18975108, 0.99615854, 0.81126738, 0.89543116],
       [0.66358338, 0.079853  , 0.21406522, 0.95371644, 0.87707988],
       [0.67113613, 0.03235564, 0.53383392, 0.39483589, 0.76196512],
       [0.51965626, 0.93558013, 0.33507298, 0.43721332, 0.44203479]])

### randn
Este método devuelve una muestra en la distribución "normal estándar" $[\sigma = 1]$ [referencia](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randn.html?highlight=randn#numpy.random.randn)

In [20]:
np.random.randn(2)

array([-0.49332112, -1.21224607])

In [21]:
np.random.randn(5,5)

array([[ 1.97939391, -0.32465094,  0.46740118, -0.7381133 , -1.08732245],
       [-1.79966848,  0.86837319,  1.44995506, -0.83882042,  0.33071524],
       [-1.38776489,  1.38855045,  1.58819818,  0.70634629, -1.38647877],
       [-1.52167613,  0.92624906,  0.53765054,  0.43159791, -0.35413704],
       [-1.08210748, -0.29841723, -0.94052588,  1.49545251,  0.95579783]])

### randint
genera valores aleatorios enteros [referencia](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html?highlight=randint#numpy.random.randint)

In [22]:
np.random.randint(1,100)


41

In [23]:
np.random.randint(1,100,(5,5))

array([[ 7, 80, 20, 16, 62],
       [ 7, 31, 55, 14, 82],
       [63, 95, 44, 31,  2],
       [21, 75, 10, 19, 24],
       [59, 29, 69, 63, 33]])

In [24]:
np.random.randint(1,100,10)

array([24, 91, 71, 44, 27, 54, 61, 22, 47, 50])

### seed
se puede utilizar para establecer estado aleatorio, de modo que se puedan reproducir los resultados [referencia](https://numpy.org/doc/stable/reference/random/generated/numpy.random.seed.html?highlight=seed#numpy.random.seed)

In [25]:
np.random.seed(42)


In [26]:
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [27]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [28]:
np.random.rand(4)

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

In [29]:
np.random.rand(4)

array([0.60111501, 0.70807258, 0.02058449, 0.96990985])

## Atributos y métodos de un Arreglo

In [30]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
ranarr

array([43, 29, 37,  1, 20, 32, 11, 21, 43, 24])

## Reshape
devuelve una matriz que contiene los mismos datos con una nueva forma


In [33]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [35]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

## max, min, argmax, argmin

In [36]:
ranarr

array([43, 29, 37,  1, 20, 32, 11, 21, 43, 24])

In [37]:
ranarr.max()

43

In [38]:
ranarr.argmax()

0

In [39]:
ranarr.min()

1

In [40]:
ranarr.argmin()

3

## dtype

In [41]:
arr.dtype 

dtype('int64')

In [42]:
arr2= np.array([1.2,3.4,5.6])

In [43]:
arr2.dtype

dtype('float64')

## NumPy Indexación y selección

In [44]:
arr = np.arange(0,11)

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
arr[8]

8

In [47]:
arr[1:5]

array([1, 2, 3, 4])

In [48]:
arr[8:]

array([ 8,  9, 10])

In [49]:
arr[1]

1

In [50]:
arr[0]

0

In [51]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [52]:
arr[:5]

array([0, 1, 2, 3, 4])

## Broadcasting

In [53]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
arr[0:5] = 100

In [55]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [56]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
slice_arr = arr[0:6]

In [58]:
slice_arr

array([0, 1, 2, 3, 4, 5])

In [59]:
slice_arr[:] = 99 

In [60]:
slice_arr

array([99, 99, 99, 99, 99, 99])

In [61]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## méstodo copy

In [62]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
arr_copy = arr.copy()

In [65]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
slice_arr = arr_copy[0:6]
slice_arr

array([0, 1, 2, 3, 4, 5])

In [67]:
slice_arr[:] = 99 

In [68]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Indexación de un arreglo 2D (matrices)

In [71]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
arr[0]

0

In [83]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [84]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [85]:
arr_2d[1]

array([20, 25, 30])

In [86]:
arr_2d[1,1]

25

In [87]:
arr_2d[2,2]

45

In [88]:
arr_2d[:1,:1]

array([[5]])

In [89]:
arr_2d[:2,:2]

array([[ 5, 10],
       [20, 25]])

In [90]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

In [91]:
arr_2d[0][1:]

array([10, 15])

### Crear un arreglo de números enteros del 0 al 35 y después con ese arreglo crear una matriz de 6x6

In [92]:
matriz = np.arange(36)

In [93]:
matriz

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [94]:
m = matriz.reshape(6,6)

In [95]:
m

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [98]:
m_r = m[:,2]
m_r

array([ 2,  8, 14, 20, 26, 32])

In [100]:
m_n = m[0,3:5]
m_n

array([3, 4])

In [103]:
m_v = m[4:,4:]
m_v

array([[28, 29],
       [34, 35]])

In [104]:
m[2:5:2,::2]

array([[12, 14, 16],
       [24, 26, 28]])

In [105]:
m[2::2,::2]

array([[12, 14, 16],
       [24, 26, 28]])

## Selección condicional 

In [106]:
arr = np.arange(1,11)

In [107]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [108]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [110]:
bool_arr = arr>4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [111]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [112]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [115]:
arr[(arr>4) & (arr<8)]

array([5, 6, 7])

## Aritméticas con Arreglos

In [116]:
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [117]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [118]:
arr*arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [119]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [120]:
arr/arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [121]:
1/arr

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ])

In [122]:
arr**3

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000])

## Funciones para arreglos

In [123]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [124]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [125]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [126]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [127]:
arr.sum()

55

In [128]:
arr.mean()

5.5

In [129]:
arr.max()

10

In [130]:
arr.var()

8.25

In [131]:
arr.std()

2.8722813232690143

In [132]:
arr_2d = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])

In [133]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [135]:
arr_2d[1].sum()

26

In [136]:
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

In [137]:
arr_2d.sum(axis=1)

array([10, 26, 42])