<div style="text-align: right"> 00/02 </div>
<h1><center>Repaso de la Librería NumPy</center></h1>

# NumPy 

NumPy es una poderosa librería de álgebra lineal para Python. Lo que lo hace tan importante es que casi todas las librerías en el ecosistema de <a href='https://pydata.org/'>PyData</a> (pandas, scipy, scikit-learn, etc.) utilizan NumPy como uno de sus principales componentes básicos. 

NumPy también es increíblemente rápido, ya que tiene enlaces a bibliotecas C.

Aquí repasaremos los conceptos básicos de NumPy.

## Usando NumPy


In [1]:
import numpy as np


NumPy tiene muchas funciones y capacidades integradas. No veremos todos, nos centraremos en algunos de los aspectos más importantes de NumPy qué nos serán de utilidad en el curso como son: vectores, arreglos, matrices y generación de números aleatorios. 

# Arreglos en NumPy 

Los arreglos de NumPy son la principal forma en que utilizaremos esta librería a lo largo del curso. Los arreglos en NumPy se construyen de dos formas: vectores y matrices. Los vectores son matrices estrictamente unidimensionales (1D) y las matrices son elementos en 2D (pero se debe tener en cuenta que una matriz puede tener solo una fila o una columna) no son estrictamente cuadradas.

## Creando Arreglos en NumPy

### De una Lista de Python 

Podemos crear un arreglo directamente de una lista o listas de listas:



In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Métodos incorporados en NumPy

Hay muchas formas de como generar arreglos usando métodos incorporados.

### arange

Devuelve valores espaciados uniformemente dentro de un intervalo dado. [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.arange.html)]

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### Creando arreglos de Ceros (zeros) y Unos (ones)

Podemos generar matrices de ceros ó unos. [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.zeros.html)]

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones(3)

array([1., 1., 1.])

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace 
Este método devuelve números espaciados uniformemente durante un intervalo especificado.[[referencia](https://www.numpy.org/devdocs/reference/generated/numpy.linspace.html)]

In [15]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [16]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

<font color=green>Note que `.linspace()` *incluye* el valor de paro. Para obtener un arreglo con fracciones comunes, hay que aumentar el numero de elementos:</font>

In [17]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

### eye

Mediante este método podemos crear la matriz identidad.[[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.eye.html)]

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 
Numpy también tiene muchas formas de crear arreglos de números aleatorios:

### rand

Mediante este método podemos crear un arreglo de un tamaño dado con muestras aleatorias de una distribución uniforme en el intervalo ``[0, 1)``.[[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.rand.html)]

In [19]:
np.random.rand(2)

array([0.57767023, 0.56940935])

In [20]:
np.random.rand(5,5)

array([[0.01115088, 0.29681944, 0.6519738 , 0.52336611, 0.40402961],
       [0.62051258, 0.13002774, 0.68453395, 0.23924165, 0.55949704],
       [0.98392184, 0.922178  , 0.03954266, 0.77993686, 0.16116608],
       [0.51558489, 0.10200572, 0.81094867, 0.5983574 , 0.77677777],
       [0.47915878, 0.43839935, 0.97514364, 0.39245203, 0.66986166]])

### randn

Este método devuelve una muestra (o muestras) de la distribución "normal estándar" [σ = 1] A diferencia de **rand**, que es uniforme, es más probable que aparezcan valores más cercanos a cero. [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randn.html)]


In [21]:
np.random.randn(2)

array([ 0.29078686, -0.46292709])

In [22]:
np.random.randn(5,5)

array([[-0.58795945,  2.08505229, -2.86425939, -0.00741425,  0.77294625],
       [-0.59176469, -0.87481796,  0.42812501, -0.69386553,  0.8105541 ],
       [ 0.69367838, -0.46372991,  0.09156275, -1.5382325 ,  0.98879714],
       [-2.12555498,  0.74139265, -0.50523341,  0.83584888,  1.04591671],
       [ 2.93745323,  0.61464418,  0.04143181,  0.75460735, -0.60287126]])

### randint
Devuelve números enteros aleatorios de un intervalo `mínimo` (inclusive) a `máximo` (exclusivo).  [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randint.html)]

In [23]:
np.random.randint(1,100)

34

In [24]:
np.random.randint(1,100,10)

array([ 2, 65, 34, 91, 11, 24, 24, 84,  1, 97])

### seed
Se puede utilizar para establecer el estado aleatorio, de modo que se puedan reproducir los mismos resultados "aleatorios". [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.seed.html)]

In [22]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [23]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

## Atributos y métodos de un Arreglo

Analicemos algunos atributos y métodos útiles para un arreglo:

In [25]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
ranarr

array([35, 19, 33, 22, 40, 30, 28, 11, 15,  8])

## Reshape
Devuelve una matriz que contiene los mismos datos con una nueva forma. [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.reshape.html)]

In [27]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max, min, argmax, argmin

Estos son métodos útiles para encontrar valores máximos o mínimos. O para encontrar el índice donde tenemos valores máximos o mínimos:

In [28]:
ranarr

array([35, 19, 33, 22, 40, 30, 28, 11, 15,  8])

In [29]:
ranarr.max()

40

In [30]:
ranarr.argmax()

4

In [31]:
ranarr.min()

8

In [32]:
ranarr.argmin()

9

## Shape

Shape es un atributo que tienen los arreglos (no un método): [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.shape.html)]

In [33]:
# Vector
arr.shape

(25,)

In [34]:
# Observe qué ahora tenemos los paréntesis
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [35]:
arr.reshape(1,25).shape

(1, 25)

In [36]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [37]:
arr.reshape(25,1).shape

(25, 1)

### dtype

Podemos también obtener el tipo de datos del objeto en el arreglo. [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.dtype.html)]

In [41]:
arr.dtype

dtype('int64')

In [42]:
arr2 = np.array([1.2, 3.4, 5.6])
arr2.dtype

dtype('float64')