<div style="text-align: right"> 01/02 </div>
<h1><center>Repaso de la Librería NumPy</center></h1>

# NumPy Indexación y selección

En este apartado veremos como seleccionar elementos o grupos de elementos de un arreglo.

In [1]:
import numpy as np

In [2]:
#creamos el arreglo
arr = np.arange(0,11)

In [3]:
#mostramos
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Selección e indexación mediante Brackets
La forma más sencilla de elegir uno o algunos elementos de un arreglo es muy similar a las listas de Python:

In [4]:
#obtener el valor dado un índice
arr[8]

8

In [5]:
#Obtener los valores dado un intervalo de índices
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[0:5]

array([0, 1, 2, 3, 4])

## Broadcasting

Los arreglos en NumPy se diferencian de las listas normales de Python debido a su capacidad para reasignar valores. Con las listas, solo puede reasignar partes de una lista con partes nuevas del mismo tamaño y forma. Es decir, si quisiera reemplazar los primeros 5 elementos de una lista con un nuevo valor, tendría que pasar una nueva lista de 5 elementos. Con los arreglos de NumPy, podemos reasignar un solo valor a través de un conjunto más grande de valores:


In [9]:
#asignando un valor mediante un rango de indices (Broadcasting)
arr[0:5]=100

#mostrar
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
# Reseteando el arreglo
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
#Notas importantes sobre subarreglos
slice_of_arr = arr[0:6]

#mostrar
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [12]:
#cambiamos el subarreglo
slice_of_arr[:]=99

#mostrándolo nuevamente
slice_of_arr

array([99, 99, 99, 99, 99, 99])

¡Ahora observe que los cambios también ocurren en nuestro arreglo original!

In [11]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Los datos no se copian, sólo es un pedazo del arreglo original.

In [13]:
#Para obtener una copia, se necesita utilizar el método copy
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexación de un arreglo 2D (matrices)

Lo forma general es: **arr_2d[row][col]** o **arr_2d[row,col]**.

In [15]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#mostrar
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [16]:
#indexación de una fila
arr_2d[1]

array([20, 25, 30])

In [17]:
# Obtener un valor individual de la matriz
arr_2d[1][0]

20

In [18]:
# Obtener un valor individual de la matriz
arr_2d[1,0]

20

In [17]:
# Obtener un pedazo del arreglo 2D

#tamaño (2,2) pedazo superior derecho de la matriz
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [19]:
#obtener toda la fila inferior
arr_2d[2]

array([35, 40, 45])

In [20]:
#obtener toda la fila inferior
arr_2d[2,:]

array([35, 40, 45])

## Más sobre indexación
Indexar una matriz 2D puede ser un poco confuso al principio, especialmente cuando se tiene un mator tamaño en la matriz.

Una imagen útil para entender el concepto de indexación:

<img src= 'numpy_indexing.png' width=500/> 

## Selección Condicional

Este es un concepto muy fundamental que nos servirá en la librería de Pandas más adelante, ¡asegúrate de entender esta parte!


In [21]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [23]:
bool_arr = arr>4

In [24]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [25]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [26]:
#Una manera más directa
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
# dado un valor 
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])