<div style="text-align: right"> 02/02 </div>
<h1><center>Repaso de la Librería NumPy</center></h1>

# Operaciones con NumPy

## Aritméticas

Podemos realizar fácilmente aritmeticas como * arreglo con arreglo * , o * escalar con arreglo *. Veamos algunos ejemplos: 

In [1]:
import numpy as np
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [3]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [4]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
# Esta operación manda un warning por la división por cero, pero no es un error!
# simplemente llena el lugar con un nan
arr/arr

/home/deloga/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [6]:
# Esto también arroja un warning (pero no un error) rellena el valor con inf
1/arr

/home/deloga/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [7]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

## Funciones universales en los Arreglos

NumPy viene con muchass [funciones universales en los arreglos](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), or <em>ufuncs</em>, que son esencialmente operaciones matemáticas que se pueden aplicar al arreglo.<br>Veamos algunas funciones más comunes:

In [8]:
# obtener la raíz
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [9]:
# calcular la exponencial (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [10]:
# funciones trigonométricas como el seno
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [11]:
# obtener el logaritmo natural
np.log(arr)

/home/deloga/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

## Resumen de Estadística sobre Arreglos

NumPy también ofrece métodos estadísticos como <em> sum </em>, <em> mean </em> y <em> max </em>. 

In [12]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr.sum()

45

In [14]:
arr.mean()

4.5

In [15]:
arr.max()

9

<strong>Otros métodos estadísticos son:</strong>
<pre>
arr.min() regresa 0                   mínimo
arr.var() regresa 8.25                varianza
arr.std() regresa 2.8722813232690143  desviación estándar
</pre>

## Lógica para el eje (axis)

Cuando trabajamos con arreglos bidimensionales, debemos considerar filas y columnas. En términos de un arreglo, el eje 0 (cero) es el eje horizontal (filas) y el eje 1 es el eje vertical (columnas). Los valores (0,1) corresponden al orden en el que método <tt> arr.shape </tt> da como salida.

Veamos cómo afecta esto a nuestros cálculos estadísticos resumidos de arriba.


In [18]:
# creamos un arreglo
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

Dando como entrada <tt>axis=0</tt>, estamos devolviendo la suma del arreglo a lo largo del eje vertical, esencialmente <tt>[(1+5+9), (2+6+10), (3+7+11), (4+8+12)]</tt>

<img src='axis_logic.png' width=400/>

In [20]:
arr_2d.shape

(3, 4)

Esto nos dice que <tt>arr_2d</tt> tiene 3 filas y 4 columnas.

En <tt>arr_2d.sum(axis=0)</tt>, se sumó el primer elemento de cada fila, luego el segundo elemento y así sucesivamente.

Entonces, ¿qué debería <tt>arr_2d.sum(axis=1)</tt> regresar?

In [22]:
arr_2d.sum(axis=1)

array([10, 26, 42])